// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    url: "https://m.media-amazon.com/images/I/61mIq2iJUXL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
    summary: "Authored by Gayle Laakmann McDowell, Cracking the Coding Interview is the definitive guide to navigating the rigorous technical hiring processes used by top-tier software companies. The book demystifies what happens behind closed doors during recruiter screens and technical panels, offering actionable advice on resume preparation, handling behavioral inquiries, and negotiating job offers.",
  },
  {
    id: 2,
    title: "Atomic Habits",
    url: "https://m.media-amazon.com/images/I/81ANaVZk5LL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
    summary: "In his interviews, Atomic Habits author James Clear emphasizes that lasting change stems from the compound interest of tiny, 1% daily improvements rather than massive, overnight shifts. He advocates for building sustainable systems through identity-based habits, focusing on becoming a certain type of person rather than just achieving specific goals.",
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    url: "https://m.media-amazon.com/images/I/81gTRv2HXrL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
    summary: "Can't Hurt Me by David Goggins is a powerful memoir and self-help guide. It tells the story of his life. He went from a scared, overweight, and abused kid to a top Navy SEAL and endurance athlete. The book shows how to use pain and hard work to build a strong mind.",
  },
  {
    id: 4,
    title: "Deep Work",
    url: "https://m.media-amazon.com/images/I/91nujEwIpYL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
    summary: "Deep work is professional activity performed in a state of distraction-free concentration that pushes your cognitive capabilities to their absolute limit. Coined by author Cal Newport, this focused effort creates new high-value output, sharpens your personal skills, and produces results that are exceptionally difficult for others to replicate.",
  },
  {
    id: 5,
    title: "The 10X Rule",
    url: "https://m.media-amazon.com/images/I/71hjq42hvGL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
    summary: "The 10X Rule by Grant Cardone is a goal-setting and mindset philosophy stating that people drastically underestimate the targets they set and the effort needed to reach them. To succeed, you must multiply your goals by ten and commit to taking ten times the amount of massive action.",
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    url: "https://m.media-amazon.com/images/I/616OvChM3RL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
    summary: "In Grant Cardone's book Sell or Be Sold, Chapter 2 focuses on the core concept that salespeople make the world go round and that basic persuasion dictates every interaction in daily life. You are either actively influencing others or being influenced by them.",
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    url: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
    summary: "Rich Dad Poor Dad by Robert Kiyosaki contrasts the differing financial philosophies of his biological father (the 'poor dad'), a highly educated government employee who struggled with debt, and his best friend's father (the 'rich dad'), an uneducated dropout who became a wealthy entrepreneur. The book advocates making money work for you rather than working for a paycheck",
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    url: "https://m.media-amazon.com/images/I/71+SWQ6xj1L._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
    summary: "The Cash Flow Quadrant is a model by Robert Kiyosaki that categorizes income generation into four distinct profiles. It splits into the left side—Employee (E) and Self-Employed/Small Business (S), where individuals trade time for linear income—and the right side—Business Owner (B) and Investor (I), where systems and money work to generate passive wealth.",
  },
  {
    id: 9,
    title: "48 Laws of Power Summary",
    url: "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
    summary: "The 48 Laws of Power by Robert Greene is a popular guide on how to gain, keep, and defend control over others. The book uses stories from history, philosophy, and war to show how power works in everyday life. It teaches readers to be smart, careful, and strategic rather than emotional.",
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    url: "https://m.media-amazon.com/images/I/91wOERyhh7L._UF1000,1000_QL80_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
    summary: "In The 5 Second Rule by Mel Robbins, the author presents a simple metacognitive tool: counting backward from five to one (5-4-3-2-1) and moving immediately into physical action. Created during a severe personal and financial low point, this method is designed to interrupt hesitation, silence self-doubt, and bypass the brain's excuses before it can stop you.",
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    url: "https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
    summary: "Published in 1936 by Dale Carnegie, How to Win Friends and Influence People is a timeless self-help classic centered on fundamental human relations, empathy, and effective communication. The core premise argues that handling people successfully requires moving past ego to understand emotional drivers like pride, vanity, and an innate desire to feel important.",
  },
  {
    id: 12,
    title: "Mastery",
    url: "https://m.media-amazon.com/images/I/51V3121nmkL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
    summary: "In Mastery by Robert Greene, the author argues that true greatness is not born from innate talent, but from a repeatable process. By studying historical figures like Albert Einstein and Leonardo da Vinci, alongside modern experts, Greene shows that anyone can achieve elite expertise by following a structured developmental journey.",
  },
];